[mcps]

[mcps.builtins]
portfolio = { auth = "None", type = "remote", url = "https://portfolio-agent-app.jollysand-88b78b02.eastus.azurecontainerapps.io/mcp", headers = ["x-scheduled-secret: portfolio-scheduler-2026"] }
calendar = { type = "calendar" }
mail = { type = "mail" }
teams = { type = "teams" }
