// Copyright (c) Microsoft Corporation. Licensed under the MIT License.
// Portfolio Manager Digital Worker — Monthly Commentary Generator
//
// Generates a monthly fund commentary suitable for client reports.
// Pulls portfolio performance, key events, sector allocation, and
// uses LLM to produce professional commentary.
//
// Triggered via /api/scheduled/commentary — recommended: 1st business day of month

import { mcpClient } from './mcp-client';
import { getStandaloneClient } from './client';
import { sendEmail } from './email-service';
import { postToChannel } from './teams-channel';
import { generateCommentaryDocx } from './doc-generator';

const MANAGER_EMAIL = process.env.MANAGER_EMAIL || '';
const MANAGER_NAME = process.env.MANAGER_NAME || 'Manager';

export async function runMonthlyCommentary(): Promise<{ status: string; wordCount: number }> {
  console.log(`[Commentary] Monthly commentary generation starting at ${new Date().toISOString()}`);

  // Gather portfolio data
  const [holdings, pipeline, dashboard] = await Promise.allSettled([
    mcpClient.getPortfolioHoldings(),
    mcpClient.getCrmPipeline(),
    mcpClient.getPortfolioDashboard(),
  ]);

  // Get quotes for top holdings
  const quotes: Array<{ symbol: string; data: unknown }> = [];
  try {
    const holdingsVal = holdings.status === 'fulfilled' ? holdings.value : null;
    if (holdingsVal) {
      const holdingsStr = typeof holdingsVal === 'string' ? holdingsVal : JSON.stringify(holdingsVal);
      const match = holdingsStr.match(/\[[\s\S]*\]/);
      if (match) {
        const arr = JSON.parse(match[0]);
        const tickers = arr.filter((h: any) => h.Ticker && h.Shares > 0).map((h: any) => h.Ticker).slice(0, 10);
        const results = await Promise.allSettled(tickers.map((t: string) => mcpClient.getBasicFinancials(t)));
        results.forEach((r, i) => {
          if (r.status === 'fulfilled') quotes.push({ symbol: tickers[i], data: r.value });
        });
      }
    }
  } catch (e) {
    console.warn('[Commentary] Quote fetch error:', e);
  }

  const truncate = (d: unknown, maxLen = 6000): string => {
    const s = typeof d === 'string' ? d : JSON.stringify(d);
    return s.length > maxLen ? s.substring(0, maxLen) + '...' : s;
  };

  const prevMonth = new Date();
  prevMonth.setMonth(prevMonth.getMonth() - 1);
  const monthName = prevMonth.toLocaleDateString('en-GB', { month: 'long', year: 'numeric' });

  const client = await getStandaloneClient();
  const commentary = await client.invokeAgentWithScope(`You are a portfolio manager's digital worker. Generate a professional monthly fund commentary for ${monthName} that could be sent to investors or used in client reports.

PORTFOLIO DATA:
${truncate(holdings.status === 'fulfilled' ? holdings.value : 'unavailable')}

MARKET QUOTES:
${truncate(quotes)}

DASHBOARD:
${truncate(dashboard.status === 'fulfilled' ? dashboard.value : 'unavailable')}

Write the commentary with these sections:
1. **Market Environment** — Brief macro context for the month
2. **Fund Performance** — How the portfolio performed (use available data)
3. **Key Contributors & Detractors** — Top 3 each, with specific attribution
4. **Portfolio Activity** — Any changes made, new positions, exits
5. **Sector Positioning** — Current allocation and rationale
6. **Outlook** — Forward-looking view, risks and opportunities

RULES:
- Write in third person ("The fund...", "The portfolio...")
- Professional, institutional tone — suitable for client reports
- ~500-700 words
- Include specific data points where available
- Be balanced — acknowledge both positives and negatives
- Output as clean HTML with proper headings`) || '';
  const wordCount = commentary.split(/\s+/).length;

  console.log(`[Commentary] Generated ${wordCount}-word commentary`);

  // Send to PM for review
  const html = `
    <div style="font-family:Segoe UI,sans-serif;max-width:700px;margin:0 auto">
      <div style="background:#1a237e;color:white;padding:16px 20px;border-radius:8px 8px 0 0">
        <h2 style="margin:0">📝 Monthly Commentary Draft — ${monthName}</h2>
        <p style="margin:4px 0 0;opacity:.85;font-size:12px">Generated by your digital worker for review</p>
      </div>
      <div style="background:#fff;padding:20px;border:1px solid #e0e0e0;border-top:none;line-height:1.6;font-size:14px">
        ${commentary}
        <hr style="margin:20px 0;border:none;border-top:1px solid #e0e0e0">
        <p style="font-size:11px;color:#999;font-style:italic">This is a draft generated by your Portfolio Manager Digital Worker. Please review and edit before distributing to clients.</p>
      </div>
    </div>`;

  if (MANAGER_EMAIL) {
    try {
      // Generate Word document for attachment
      const docxBuf = await generateCommentaryDocx(
        monthName,
        commentary,
        holdings.status === 'fulfilled' ? holdings.value : [],
      );
      console.log(`[Commentary] Generated .docx (${(docxBuf.length / 1024).toFixed(0)} KB)`);

      await sendEmail({
        to: MANAGER_EMAIL,
        subject: `📝 Monthly Commentary Draft — ${monthName}`,
        body: html,
        isHtml: true,
        attachments: [{
          name: `Fund-Commentary-${monthName.replace(/\s+/g, '-')}.docx`,
          contentType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
          content: docxBuf,
        }],
      });
      console.log('[Commentary] Draft emailed to manager with Word attachment');
    } catch (err) {
      console.warn('[Commentary] Email failed:', (err as Error).message);
    }
  }

  await postToChannel(`<h3>📝 Monthly Commentary — ${monthName}</h3><p>Draft commentary generated and emailed to ${MANAGER_NAME} for review.</p>`);

  return { status: 'complete', wordCount };
}
